### ISSUE TITLE
Spelling error in main page

### ISSUE THREAD

**Issue by yogwoggf** [Fasteroid/fasteroid.github.io#5]
Found a spelling error in your main page.

https://github.com/Fasteroid/fasteroid.github.io/blob/c116dcbdd31b4385bfaa64bff9fd03aa97b2d634/index.html#L56

**Comment by yogwoggf** [comment]
I'd suggest using WebStorm, the trial version @Fasteroid . Once you use WebStorm, you can't go back, it would have also caught this mistake for you.

**Comment by Derpius** [comment]
Found a few others:

https://github.com/Fasteroid/fasteroid.github.io/blob/90456142d635fc9e3818d2b667bb53295a17d490/desmos-double-tangents.html#L48

https://github.com/Fasteroid/fasteroid.github.io/blob/02bb64b9d797540b90cb97075b973da9297930f1/desmos-galton-board.html#L46

https://github.com/Fasteroid/fasteroid.github.io/blob/02bb64b9d797540b90cb97075b973da9297930f1/desmos-nearby-points.html#L42

Haven't checked the rest of the files, but recommend either WebStorm as @yogwoggf says above, or the VSCode spellchecker extension

**Comment by Fasteroid** [comment]
> Found a few others:
I don't see anything wrong with the linked lines.  They are line breaked to avoid being too long to fit in a single line in vscode.

@yogwoggf I'm aware of the random slash, and that will be fixed next commit.

@Derpius Thanks for recommending the spellchecker extension; I didn't know that was a thing.
