### ISSUE TITLE
Wrong discord account linked

### ISSUE THREAD

**Issue by Kilometres** [Fasteroid/fasteroid.github.io#7]
In the [E2 Raytracing page](https://github.com/Fasteroid/fasteroid.github.io/blob/main/expression2-raytracer.html) you links Speed and Vurv's accounts, but both links go to speed's account. This is a **tremendous mistake** as it devalues Vurv's work.

![image](https://github.com/Fasteroid/fasteroid.github.io/assets/39900063/93de858d-bb5b-4a81-9a2a-cebdfd59020b)

**Comment by Fasteroid** [comment]
my bad, will fix
