### ISSUE TITLE
Use coldfusion

### ISSUE THREAD

**Issue by Kilometres** [Fasteroid/fasteroid.github.io#9]
ColdFusion is a commercial rapid web-application development computing platform. ColdFusion is most often used for data-driven websites or intranets, but can also be used to generate remote services such as REST services, WebSockets, SOAP web services or Flash remoting.

Helpful link: https://www.adobe.com/uk/products/coldfusion-family.html

**Comment by Fasteroid** [comment]
No.

**Comment by yogwoggf** [comment]
> No.

Seems kinda harsh? Can you elaborate on why?

**Comment by Fasteroid** [comment]
ColdFusion is a serverside scripting language.  I cannot use a serverside scripting language on github pages.
Not saying I won't use it on some future project, this just isn't the one for it.
